code-charity/youtube

popup/template-parts/player.js
Only being able to switch between the same values YouTube  offers out of the box doesn't make a lot of sense.
=> Changing the Playback-Speed in smaller steps.

template/template-parts/settings.js
Hi, my first constribution with a very low priority fix. The Home label in the settings is shown as "undefined".
=> Fix (LOW): Settings Home label shown as "undefined"

youtube/js/features/settings.js
This will fix the issue that breaks scrolling using the scrollbar when the icon is disabled and the code fails reading an undefined object.
=> Fix: "Cannot read property 'getBoundingClientRect' of null" when Icon is Disabled

template/template-parts/settings.js
I've changed ``successfullyImportedSettings`` to ``settingsSuccessfullyImported``.
The strings between the template and translations were different.
**_locales\\...\messages.json**
```JSON
"settingsSuccessfullyImported": {
"message": "Settings successfully imported"
},
```
**template\template-parts\settings.js** [BEFORE]
```JAVASCRIPT
message: {
type: 'text',
label: 'successfullyImportedSettings',
style: {
'width': '100%',
'opacity': '.8'
}
},
```
I went with the least-edit path, I hope it's good enough.
=> A fix for the SUCCESSFUL SETTINGS IMPORT message.

src/youtube/js/features/channel.js
This should fix the channel_default_tab setting not being used if a channel's URL contains "/c/", rather than "/user/" or "/channel/". (e.g. https://www.youtube.com/c/F1)
=> Update channel.js to search for channel URLs containing /c/ when setting the default tab

src/youtube/js/features/general.js
This is a partial fix for the broken homepage redirect feature described in issue #567. It's a partial fix because it seems to only work on the YouTube logo, and not the sidebar. The fix works by removing all event listeners on the element, thus defaulting to the href provided by the browser.
=> Partial fix for homepage

youtube-scripts.js
Blacklist only worked if URL contains "channel" and not "c".
If a channel with "c" gets blocked then the video_id ends up being "https:" resulting in everything getting blocked
=> Fix #328 by getting the correct channel id

content-styles.css, youtube-scripts.js
Seems like `}` is missing. Because of that mini-player does not work as it should when browser is in dark mode.  
Also added dispatch event on mini-player resize, so progress bar will work properly.
=> Fix miniplayer

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, popup.js, youtube-scripts.js
Non HDR video options are not available when HDR is enabled in windows. Browser HDR is extremly laggy so users who have HDR enabled on windows currently have no way of playing SDR videos for smooth playback.
Add feature to force SDR which sets Window.screen.pixelDepth to 24 for computers that support 30+ (HDR) to trick Youtube into thinking HDR is not supported, allowing the user to select non HDR videos when HDR is enabled in windows.
=> Add feature to force SDR for ImprovedTube#694

content-styles.css
Fixes #794 - I found that the cause was that an older version of IT had used the value "normal" for the player color, but newer versions did not have support for that value, leading to the player bar (And all the other elements which are affected) being greyed out. This simply adds support for that value on the CSS side.
=> Implemented backwards-compatibility with 'normal'

README.md
The file was removed in below commit and caused, at least myself, a moment of confusion for how to run things
eb4530677b13d18ae3cce855802782f9fb3a447a
=> Remove reference to build.py

_locales/en/messages.json, popup.js, youtube-scripts.js
+ Added an option that allows hiding (removal) of the buttons overlaid on thumbnails. See #771.
(Now using CSS to remove them rather than `remove()`)
=> Added option to hide thumbnail overlays

youtube-scripts.js
Changed from non-standard event.path to standarized event.composedPath(). This eliminates error in firefox which was being printed in console everytime mouse was moved.
=> Changed from non-standard event.path to standarized event.composedPath()

popup.js
https://www.w3.org/TR/DOM-Level-3-Events/#event-flow-default-cancel 'Default actions are usually performed after the event dispatch has been completed, but in exceptional cases they may also be performed immediately before the event is dispatched.'
=> onclick/onchange order ambiguity fix 

content-styles.css
ImprovedTube not hiding the skip overlay as YouTube change the class name from ytp-doubletap-ui to ytp-doubletap-ui-legacy.
=> Fixed skip overlay not working

youtube-scripts.js
Looks like youtube player also sets session storage volume if you
increase it manually.
=> Sync player volume between local and session on volume shortcuts

content-styles.css
Fixes Limit Page Width so it doesn't break when watching a vertical or square aspect ratio video.
https://github.com/code-for-charity/YouTube-Extension/issues/1244
Appears to work without issue in both the regular player and the theater player.
Modify as you see fit.
=> Limit Page Width Vertical Videos Bug Fix

ui/satus/satus.css, ui/styles.css
Fixed mixer card popup slider section color: https://github.com/code-for-charity/YouTube-Extension/issues/1283
- satus.css | created var:  --satus-slider-background for theming slider colors
- style.css | chnaged var: satus-section-card-background to satus-section-opaque-background (avoid confusion) and used it to color mixer section as well as card sections
Fixed key color readability: https://github.com/code-for-charity/YouTube-Extension/issues/1270
- added text color for keys, used #575757 to meet a11y standards
used https://color.a11y.com to ensure contrasts were ideal
=> a11y color updates

content-styles.css
Addresses  issues #1272 and #1278 caused by YouTube changing `<video>` tag to `object-fit:cover` instead of old `object-fit:containt`. Not sure if the CSS was put in the right category or if it should apply to other scaling modes.
=> Fix for fit_to_window and full_window

youtube-scripts.js
The video is loaded twice, once on init and once after windows size is determine which resulted in video played for a few second on #1297 as it did not pause the video on time for the second time. Therefore, I set it so that the first time stop the video so video is not preloaded, which give the system time to pause the video on second load.
=> Improved disabled autoplay

ui/satus/satus.js
User can remove pre-define shortcut. (however it does not disable youtube respond to those keypress)
Close #1301
=> Added "Empty" button to shortcut

youtube-scripts.js
Fix "DEFAULT CHANNEL TAB" set incorrect channel link to video author when playlist play the next video in playlist.
Fix #1333
=> Fix incorrect channel link for playlist

youtube-scripts.js
=> Fixed Issue #1395

_locales/en_GB/messages.json, _locales/en_US/messages.json, _locales/es_419/messages.json
Instead of deleting the untranslated es_419, I replaced it with es so that users with es_419 will see the translated text and in the future a translator can update it to better fall in line with es_419.
=> Revert removal of locales and updates es_419 with es

content-scripts/website-context/youtube-features/shortcuts.js
This fixes the Like and Dislike shortcuts by accessing the button object rather than the higher level ytd tag.
Resolves #1525
=> fix Like+Dislike button shortcuts

content-scripts/extension-context/init.js, content-scripts/extension-context/youtube-features/general/general.js, content-scripts/website-context/youtube-features/shortcuts.js
When the header appearance is not normal/static, this change allows the header to display (as if hovered) when the search box is opened (such as from a hotkey `/`), and the header returns to its original state once the user leaves the search input. Includes patch required for custom search shortcuts to work. 
Resolves #884
=> Allow (onhover) hidden header to show when Search box focused

background.js, content-scripts/extension-context/init.js
first checked if there is a new tab opened then checked if the new tab has another video playing
=> fixed issue #1516

content-scripts/website-context/functions.js, content-scripts/website-context/youtube-features/appearance.js
there are two functions with the id chat 
the first one sets the button that is supposed to be clicked to collapse the chat and the second one  doesn't have the button so it sets the button to null
=> issue #1552

content-scripts/extension-context/youtube-features/appearance/details/details.css
`The overflow-y: unset !important;` property tells the browser to unset the vertical overflow property of this element, which means that content will not be hidden if it exceeds the height of the element.
[#1611](https://github.com/code-for-charity/ImprovedTube-for-YouTube/issues/1611)
[Anarios/return-youtube-dislike/issues/875](https://github.com/Anarios/return-youtube-dislike/issues/875)
=> Fixed ratio bar not showing.

js&css/satus.js, js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
'up next autoplay' moved next to autoplay, quality moved next to codec options
added helper modal function, "Codec h.264" sets "Codecs", "Codecs" disable "Codec h.264"
Improved modal dialog handling, clicking outside tries to Cancel, previously clicking outside just force removed dialog.
removing "block_vp8", YT doesnt use it anymore. "Codecs" works now, can pick individual codecs to block.
more work on ModalHelper, popup warnings for disabling all video decoders.
more h264/codec interaction work, now switching one automatically updates another. Preliminary optimize_codec_for_hardware_acceleration implementation. Needs a list of GPUs with supported hardware codecs.
=> Raszpl patch 2

js&css/satus.js, menu/skeleton-parts/analyzer.js, menu/styles/analyzer.css
Better handling for clicking outside modal.confirm, try cancel() first.
Explanation comment for reason behind "values as functions isFunction(value)"
https://github.com/code-charity/SATUS/issues/7 passing key instead of object
=> Raszpl patch 1

js&css/extension/www.youtube.com/appearance/player/player.css
Added overwrite to `max-height` property at `#player-wide-container` for 'Full Height' sizing.
=> feat(player.css): Fixed max-height constraint (fixes #1710)

js&css/extension/www.youtube.com/appearance/comments/comments.css, js&css/web-accessible/www.youtube.com/appearance.js
***
**Features**:
- Layout is dynamic and responsive
- Sidebars are attached and scrollable
- Added grid composition to `related` videos
- `player` width is correctly set through JS (_temporary_)
**What's missing yet?**
- Option relocation and renaming convention. This option is currently located in `Appearance -> Comments` solely as _"Sidebar"_. Instead, it should be placed in `Appearance -> Sidebar` under the name of _"Swap Sidebar with Comments"_
- Many styles should be extracted in their own setting options, such as: 
- _"Comments as Sidebar"_ (currently available only on width 1984px+. Zoom at 80% to try)
- _"Comments Sidebar - To the left"_
**What's not working with `Comments -> Sidebar` activated?** 
- Any `Player -> Player Size` other than "_normal_"
- `Sidebar -> To The Side!` …
=> Comments: Sidebar update

js&css/extension/www.youtube.com/appearance/details/details.css, js&css/web-accessible/functions.js
I tried to fix disable autoplay play for a few mili second before pause when video is open on new tab. On my computer, it is fixed but not sure will it work for slower device, so i also did some optimization for startup code hoping to fix the problem.
This PR also update hide detail button svg code
=> Autoplay fix & more

js&css/extension/www.youtube.com/styles.css
fixed coloring issue for description hyperlinks
=> fix: #1732

js&css/web-accessible/www.youtube.com/appearance.js
@WhiteMasky Hi, I worked over the issue, and fixed it.I am attaching a  video URL [Working Video Drive Link](https://drive.google.com/file/d/1ug9nJzwmsxbceAiyihEBUz-cJReWQAQB/view?usp=sharing).
I did changes in js&css/web-accessible/www.youtube.com/appearance.js
**Original Code**
**Changes from my side**
I don't know what cookie to be set when theater mode is off.
Improvement suggesting are welcomed.
=> rakeshdhariwal/issue:#1736 fixed unable to get default setting when forced theater mode is turned off

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
player.js 
fixing playerPlaybackSpeed
- music detection works again
- clicking "(Force playback speed even for music?)" triggers immediate change
- disabling "Forced playback speed, speed-watching" correctly restores normal playback speed
- no longer setting setInterval without any reason on every page load
Update functions.js
- removed unused parameter
=> playerPlaybackSpeed patch

js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/blacklist.js
I fixed the channel name regex again and refactored it into the `ImprovedTube.regex.channel` object, so that it doesn't need to be changed everywhere if something changes.
Furthermore I noticed a missing action in the `ImprovedTube.messages.send()` call, that prevented channels from actually getting added to the blacklist.
Finally I updated the selectors for the blacklist css targets, so that hopefully all blacklisted videos get the dark overlay, no matter the page (channel, trending, subscriptions, ... ).
As a possible improvement, we could maybe add a switch, whether the blacklisted videos should be hidden completely or just use the dark overlay, although this could probably also be achieved by editing the `.it-blacklisted-video` css class.
=> fix blacklist feature

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/details/details.js, manifest.json, manifest3.json, menu/skeleton-parts/appearance.js
Issue #1761
Added YouTube video transcript copy feature.
You can find the option in: Appearance -> Details -> Copy transcript
=> feat: copy video transcript 

js&css/extension/www.youtube.com/appearance/comments/comments.css, js&css/extension/www.youtube.com/appearance/player/player.css, js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
This is a 'Fit To Window' toggle (part of #1445).
- Allows to quickly swap the current **Player Size** to `Old Alternative – Fit To Window`
- Works in both **Default View** and **Theater mode**. Tested with `Comments -> Sidebar` enabled
- Icon ~~stolen~~ taken from lucide-icons IIRC
There's possibly bugs with other settings I haven't tested yet
=> 'Fit To Window' Player button

js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/playlist.js, menu/skeleton-parts/playlist.js
More info is in #1805 section [2].
The option is under the Playlist menu and is defaulted off.
Works with (tested):
- open a playlist page
- open a video page (with a playlist)
- change the video in the playlist panel (video page)
- change to the mini player (with playlist)
- change video in the playlist panel (in mini player)
- navigate to a different playlist page (within YouTube, without reloading the page)
- open another video page (with another playlist)
The button may reappear with some delay when it is removed by page updates.
=> (new option) playlist popup button

js&css/web-accessible/www.youtube.com/player.js
As mentioned [here](https://github.com/code-charity/youtube/issues/1805#issuecomment-1811968427), commit #1813 ↓ was somehow lost, and this commit is bringing it back (with some refactoring and a comment).
<https://github.com/code-charity/youtube/blob/43d0cd35ebc044864b266a4c31a7aa10e16ceb73/js%26css/web-accessible/www.youtube.com/player.js#L726-L744>
=> recommitted #1813 (lost in git history)

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
Resolving Issue: #1837 
Hello, @ImprovedTube , this PR is created to resolve the issue of putting up the player buttons under one button.
Here is a detailed video as a result of changes done:
[bindingbutton.webm](https://github.com/code-charity/youtube/assets/47809197/c269c91d-a405-442e-91fc-41dd07a094a4)
**_How it works:_**
- Go to Player
- There is a button **Hamburger Menu** below the fit to window button, turn it on
- Now all the right controls will be packed in one
- When you click on Hamburger Menu the options will be show, and opacity of Hamburger Icon will reduce indicating it is clicked
- When pressed again the options will collapse in a bar.
Have a look, and please merge this PR, feel free to share suggestions if any.
=> feat: put player buttons under one button

background.js, js&css/extension/init.js, js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/player.js, js&css/web-accessible/www.youtube.com/playlist.js
<https://github.com/code-charity/youtube/blob/ca19c6ee60c7ffdb5ff420bb7264ae35cfcfa03d/js%26css/web-accessible/core.js#L273-L275>
When the first query selector for `.custom-hamburger-menu` fails, there is an optional chaining (`?.`) with `remove`, but the `()` comes after that, so it could be that it's trying to call `null()` with yields an error and the rest of the extension does not load...
With the second selector, everything's fine until it could be `null.paddingRight`, which is a problem, but even with an `?.` there, it can be `null = '0'`, which is, of course, also an error, so you need a temporary variable to check for null before setting it to something:
```JavaScript
// [...]
document.querySelector('.custom-hamburger-menu')?.remove?.(); 
// Restoring the original padding:
const …
```
=> Small fix & updated video and playlist URL-less popups

_locales/en/messages.json, js&css/extension/init.js, js&css/extension/www.youtube.com/appearance/player/player.js, menu/skeleton-parts/appearance.js
Issue #1677
feature added in appearrance -> player -> hide video title in fullscreen
It will hide the video title when the video is fullscreen and the option is enabled. Currently, this feature works for all videos, not for a category of videos
=> feat: hide video title on fullscreen

js&css/extension/www.youtube.com/appearance/player/player.css
Shrinks the player's height when in Max. Width within the page mode so there aren't black bars that continue above and below the video. Only works properly when viewing a 16:9 video within a browser window with the same aspect ratio Will have small black bars if the browser is maximised with the task bar underneath it. Should NOT be a permanent solution. The player should resize according to the video, not the other way round.
=> Update player.css to get rid of top and bottom margins on 16:9 aspect ratio using max width

js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
Modification to Fix  #1898 
**What does this PR do?**
This is a modification in continuation of PR #1899 
Feature added :
1.  Gives user the option to chose if they wish to have subtitle embedded on screenshot or not 
2. Appends the caption text in the end of the screenshot file name
=> Modification to fix #1898 - Embeds subtitle gives user the option to embed subtitle on screenshot or not

_locales/en/messages.json, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/player.js, menu/satus.js, menu/skeleton-parts/general.js
Implements #1958
I have added the option in the Ads section to allow users to choose if they want to Allow Ads for small creators and if they choose this option they will specify the number of subscribers that define the small creators (this option is hidden if the user chooses any other type of Ads like On or Off).
=> Allow ads for small creators

menu/satus.css
A black border around slider textboxes was added to help users identify the component as a textbox rather than just an item showing the current slider level.
=> Issue #1962 Fine Volume Control -- added CSS border for easier textbox identification

js&css/web-accessible/www.youtube.com/appearance.js, js&css/web-accessible/www.youtube.com/player.js
Improved the sync of the repeat and loop buttons to be visually and functionally linked when the user turns both buttons on. Before, I noticed that when one was set to on and the other was then added, the visual indicators of if the video would loop or not was indiscernable. I fixed this by detecting if the other button was active and then setting their opacities to be the same based on the current setting of the video (if looping or not). I did this through the onClick functions for each button respectfully, as well as adding an if statement check when the button is first added to ensure it is visually and functionally in sync.
=> IT/1959 Loop/Repeat Parity

_locales/en/messages.json, js&css/extension/init.js, js&css/extension/www.youtube.com/general/general.js, menu/skeleton-parts/general.js
Adds an option to disable video playback when hovering over thumbnails on the home page.
(Fixes #1785)
**How it works**:
Instead of using D-Rekk's solutions of `getEventListeners(node)` or `elem.remove()`, this solution adds an event listener to the global window object, listening for global `mouseenter` events.
Then, if the event's `composedPath` property contains an element matching "#content dtd-rich-item-renderer" (which selects the thumbnail elements that listen for the mouseenter event), the event is immediately stopped with `event.stopImmediatePropagation();`.
The event also runs before YouTube's native events by telling the event listener to trigger during the capturing phase instead of the bubbling phase.
**Notes**:
The second part of the issue (for recommended video previews in …
=> Disable Video Preview On Hover Option

js&css/extension/www.youtube.com/general/general.css
Previously, Shorts within the YouTube History and Trending pages were not hidden when they appeared outside of the Shorts section.
This fix addresses the issue by implementing the hiding logic uniformly across all sections within the History and Trending tabs. Now, Shorts are correctly hidden regardless of the section they appear in.
Changes Made:
- Inserted the hiding logic in History and Treding tabs to ensure Shorts are hidden consistently.
This resolves the issue reported in #2067.
=> Fix #2067: Shorts not hiding in History tab

js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/settings.js, js&css/web-accessible/www.youtube.com/themes.js, menu/skeleton-parts/themes.js
* Update themes.js
fixing theme switching, it was totally borked for as long as I remember
* Update themes.js
formatting
* Update core.js
fixing theme switching
* Update core.js
found another typo caused by bunched up code
* Update core.js
rewritten for readability
* Update init.js
redundant call
* functions.js formatting, indentation, added setPrefCookieValueByName
added safe setPrefCookieValueByName(name, value) for setting Cookie PREF parameters without manually grepping and messing things up. Called with empty "value" deletes "name" from PREF. Makes sure to preserve & where needed, sanitizes PREF removing broken elements.
* Update themes.js
switching PREF cookie handling to safe setPrefCookieValueByName()
* Update settings.js
formatting, youtubeLanguage switched to safe …
=> Theme swiching continued, this time working :)

js&css/web-accessible/www.youtube.com/shortcuts.js, js&css/web-accessible/www.youtube.com/themes.js
all that boasting about ""this time working" and I forgot default case  https://github.com/code-charity/youtube/pull/2076
=> forgot theme default case

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/themes.js
continuation https://github.com/code-charity/youtube/pull/2076
fix https://github.com/code-charity/youtube/issues/2105
=> themes Patch 5

menu/satus.js
nothing important, just fixing some errors/warnings thrown by linter
=> satus.js formatting, fixing some variable declarations

js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/www.youtube.com/themes.js
continuation #2076
Video description has some hardcoded text color, remove it make sure we remove cookie instead of writing 0
=> themes.js hopefully last time

js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/themes.js
get rid of setting hard style on ytd-masthead,
get rid of "ytd-masthead { background-color:' + primary_color + '!important;}", its already taken care of by defining --yt-spec-base-background
nicer removal of my_colors style
custom theme wasnt removing 'dark' Attribute from 'ytd-masthead'
cinematics style changes should also be converted into CSS
=> themes.js never ending optimizations

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/player/player.css, menu/skeleton-parts/appearance.js
Added an option to fill the screen while maintaining aspect ratio in full screen mode. This solves issue #1069
=> Added an option to remove black bars in full screen mode

_locales/en/messages.json, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
I've added an option that toggles captions when a Lyrics/karaoke video is detected. This fixes #1235 . Should note, that with most music videos, the captions get automatically disabled anyways, but this is extra for whenever it has not been configured.
=> Add option to automatically disable captions in lyrics/karaoke videos #1235

_locales/en/messages.json, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js, menu/styles/sub-options.css
Added cinema mode functionality. This solves issue #1915
=> Add Cinema Mode

.github/README.md
Add new safari installing method from source
Now github action will auto build the safari .app and upload to release when a new release is created (it take around 2min before it show on the release page)
=> Add new safari installing method

menu/index.html, menu/skeleton-parts/dark-light-switch.js, menu/skeleton.js
Add a light/dark mode icon on the left side of the search icon. 
When click on the icon, it switches between the light theme and the dark theme. 
The icon also changes to sun or moon, depends on the current theme color.
Four of the existing themes are categorized as light themes and the other four as dark themes. 
The custom theme is none of them and is not affected by any of them. It also remembers which theme color was used previously. 
When switching back to the light/dark mode, it switches to the previously used light/dark theme. 
https://github.com/code-charity/youtube/assets/37882796/4fe8a187-02f0-4439-b522-b8c574de7c36
=> Fix issue 2044

menu/satus.js
Dont save storage if new value is same as old value. The way satus works the mere act of displaying for example themes performs useless redundant writes.
Stop radio from writing on every render
Actually save just the value saved, not everything
color picker no longer writes on every render
=> Update satus.js limit writes to essential ones

menu/skeleton-parts/themes.js
can remove
"default_theme": {
"message": "default"
},
from all locales
=> Update themes.js normalizing, removing redundant data

js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/appearance.js
Handles #1910.
Fixes:
- addressing of the correct live-chat closing button element
- recalling of `livechat()` once storage got loaded (otherwise `storage.livechat` is `undefined` at this point in time)
- code indentation at one place
**One thing to note:** Terminology is now "closing" instead of "hiding". Not sure if this is important but wanted to hint on it. A "Show chat" button is still visible though, so it can be reopened again.
=> Fix Live Chat collapsing once storage loaded

js&css/web-accessible/core.js
currently we are writing on every page load, and its my fault :(
=> Update core.js limit localstorage writes to only essential ones

menu/satus.js, menu/skeleton-parts/appearance.js, menu/skeleton-parts/search.js, menu/skeleton.js
Update search.js keydown is redundant, input handles same case
Update search.js clean variable mess
Update search.js text_field was always broken 
Update satus.js removing redundant addEventListener 
All the listeners are already setup by satus.render. code here was doubling them down resulting in Search being performed twice every time.
Update satus.js respect storage: false on text-field elements 
Seatch text-field (Input) is of type component.skeleton.storage: false
Update satus.js propagate manual change 'text-field' value 
trigger 'change' event same way as in element.storage.set 
https://github.com/code-charity/youtube/blob/9c4e5f66e44bbe14cef4d59ce6f5cb1ae5e9d4fc/menu/satus.js#L785
Update satus.js more graceful handling of clicking outside of modal dialog
no more double .close() …
=> Update search.js polish, bugs fixed, remember/restore last search query and position.

_locales/ar/messages.json, _locales/bg/messages.json, _locales/ca/messages.json, _locales/cs/messages.json, _locales/da/messages.json, _locales/de/messages.json, _locales/en/messages.json, _locales/en_GB/messages.json, _locales/en_US/messages.json, _locales/es/messages.json, _locales/es_419/messages.json, _locales/fr/messages.json, _locales/it/messages.json, _locales/pl/messages.json, _locales/ru/messages.json, _locales/uk/messages.json, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
This commit is adding a feature described in https://github.com/code-charity/youtube/issues/300. Users can choose the quality to which the player will lower when the window is unfocused. When the window is focused again, the quality is coming back to the desired one. 
By mistake I closed previous pull request
+ I made the changes regarding @raszpl and @ImprovedTube comments
=> Feature #300: Reduce quality when window loses focus (from pull request #2162)

menu/skeleton-parts/active-features.js
I didnt notice active-features started glitching by showing buttons due to new search including them in results
=> Update active-features.js search returns buttons now, skip those

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
https://github.com/code-charity/youtube/issues/2137
do nothing if we fail to grab video element in time
=> Update player.js quick bodge fix for #2137

js&css/extension/init.js, js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/blocklist.js
Dynamically updated on all pages, can turn on/off and see results live without reloading page. Channel blocklist works now where channel info available in thumbnail container.
Might still break on some subpages, needs more extensive testing.
=> Blocklist overhaul for testing

js&css/web-accessible/www.youtube.com/player.js
currently only captures if user explicitly flips that options twice
Screenshot subtitles are still TINY, but thats another bug :)
=> Update player.js fix screenshot capturing subtitles

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
Pause immediately after play without relinquishing js event loop queue spot (previous settimeout gave browsers opportunity to delay pausing)
Call html video element pause() first, it seems faster?
Finally remove autoplayDeniedOnce. YT is autostarting most videos couple of times, autoplayDeniedOnce was breaking autoplayDisable.
Final result is our autoplayDisable no longer plays up to couple seconds before pausing. Added bonus of moving autoplayDisable below calling original.apply(this, arguments) is any problems in autoplayDisable can no longer prevent/break Play.
=> Update player.js faster more reliable autoplayDisable

js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
fixes https://github.com/code-charity/youtube/issues/2273
=> add new player_quality  'disabled' option

js&css/web-accessible/init.js
https://github.com/code-charity/youtube/blob/d8065714b67e4bbb891b11eedd72ef68f0afed38/js%26css/web-accessible/www.youtube.com/appearance.js#L316-L322
called in init https://github.com/code-charity/youtube/blob/d8065714b67e4bbb891b11eedd72ef68f0afed38/js%26css/web-accessible/init.js#L106
appearance.js:320 Uncaught TypeError: Cannot read properties of undefined (reading 'click')
at ImprovedTube.livechat (appearance.js:320:51)
at ImprovedTube.init (init.js:106:7)
at HTMLDocument.<anonymous> (core.js:176:17)
git blame shows it has been like this for at lest two years
ImprovedTube.elements.livechat stays initialized as empty object https://github.com/code-charity/youtube/blob/d8065714b67e4bbb891b11eedd72ef68f0afed38/js%26css/web-accessible/core.js#L25
until …
=> Update init.js ImprovedTube.livechat collapsed called too early

js&css/web-accessible/www.youtube.com/shortcuts.js, menu/skeleton-parts/shortcuts.js
#Fixed #1699 
Rotate shortcut issue fixed
the button is removed as told in #2302
=> Rotate shortcut updated

js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/www.youtube.com/themes.js
https://github.com/code-charity/youtube/issues/2320
=> Update styles.css Shorts Background

.github/ISSUE_TEMPLATE/bug_report.md
=> Update bug_report.md less is more

.github/workflows/js-lint-test.yml, jest.config.js, js-lint-test.yml, package-lock.json, package.json, tests/unit/core.test.js
Description:
This pull request focuses on improving testing and code quality.
Changes
-New package.json file to add Jest and JSLint
-Added Jest Framework: Implemented Jest using npm. Jest is now configured to run tests located in the "tests" directory.
-Added JSLint as it was suggested  as a development dependency.
-Added a GitHub Actions workflow file (js-lint-test.yml) to automate the process of running JSLint and Jest tests. This workflow showcases all the JSLint remarks and the testing results
Added 4  Initial Unit Tests for camelize function and events function (TRIGGER Chapter) in the core.js file. These tests are written using Jest and utilize mocking techniques, because I didn't want to export the extension object and make changes in the core.js
Created a jest.config.js file to …
=> Add Jest Framework, JSLint, and Testing Workflow

manifest.json
I was going to also fix FF compatibility, but:
~~with "service_worker": changed to "scripts":~~ https://stackoverflow.com/questions/75043889/manifest-v3-background-scripts-service-worker-on-firefox/78088358#78088358 needs both
```
"background": {
"service_worker": "background.js",
"scripts": ["background.js"]
},
```
for full cross compatibility with Firefox under V3 manifest
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support
Issue: warnins in both browsers :/. Firefox one:
```
Warning details
Reading manifest: Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest.
```
Chrome one:
`'background.scripts' requires manifest version of 2 or lower.`
=> Update manifest.json forgot comma

background.js
Keep track of connected tabs. Send only to connected tabs, send only to at most TWO tabs, one losing focus and one gaining it.
I tried experimenting with local 
```
window.addEventListener("blur", (event) => {
});
window.addEventListener("focus", (event) => {
});
```
as mentioned in https://github.com/code-charity/youtube/pull/2375 but its much worse, clicking in browser address bar takes focus away and pauses videos :/. chrome.windows.onFocusChanged  is only slightly better due to **10 year old**  Chrome bug https://issues.chromium.org/issues/41116352 :o Chrome doesnt tell us when user alt-tabs away. Firefox does send proper message and reacts to alt-tabbing just fine.
finally fixes https://github.com/code-charity/youtube/issues/2284 . Tested in Chrome, Vivaldi and FF.
=> Update background.js keep focus/blur messaging to minimum

js&css/web-accessible/www.youtube.com/player.js, js&css/web-accessible/www.youtube.com/shortcuts.js, menu/skeleton-parts/player.js
workaround for https://github.com/code-charity/youtube/issues/2341 by removing clipboard option from Firefox, saving to file works fine
=> Update player.js ClipboardItem (supported in the latest firefox too)

js&css/web-accessible/www.youtube.com/player.js
reverting #2062, implementation of https://github.com/code-charity/youtube/issues/2061 , bad idea, YT internally uses same parameter markers so we cant really distinguish between YT resuming and someone opening link with timestamp 
this.elements.player.seekTo(0) rewinds, but with side effects of triggering play()
switch from this.elements.player.seekTo(0) to this.elements.video.currentTime = 0 didnt work. YT player actually reads currentTime and will hang while hammering currentTime(whatever) if it doesnt get what it wants :0. Back to seekTo(0) with optional check for paused.
=> Update player.js reverting #2062, fixes #1342 #1652 #1904

js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
new options, compatible with old user settings
```
player_subtitles: {
text: 'auto' default YT behavior (yt detects user language and decides on its own)
text: 'enabled' always enables 
text: 'disabled' always disables
```
Can switch live without reloading page.
subtitlesLanguage no longer forces subtitles on
subtitlesUserSettings apply even when disabled - turned on later will have settings already applied
=> Captions rename for live updating, add option to force disable

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
https://github.com/code-charity/youtube/issues/2225
https://github.com/code-charity/youtube/issues/2305
=> Update functions.js ignore video previews

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
https://github.com/code-charity/youtube/pull/2400 button was still fragile and breaking :(. The only bulletproof ways of learning if subtitles are available are 
```
player.getOption('captions', 'tracklist', {includeAsr: true})
player.getSubtitlesUserSettings() 
```
also `player.isSubtitlesOn()` does work even if video has no subtitles, and `player.toggleSubtitlesOn()` is ignored in same case making both safe to call without checking.
=> Update functions.js subtitles by button turned out dead end

js&css/extension/core.js, js&css/extension/init.js, js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/blocklist.js
Tons of checks, everything is checked and initialized properly, switched to separate dedicate functions as its slightly faster.
Blocklist icon popups should be showing on video-previews now. Its not ideal, blocked thumbnails glitch a little when hovering over in search, needs some more CSS love.
https://github.com/code-charity/youtube/issues/2236
https://github.com/code-charity/youtube/issues/2334
https://github.com/code-charity/youtube/issues/2393
also adds new `ImprovedTube.createIconButton()` function in \js&css\web-accessible\functions.js Extension has ~7 icon buttons used https://github.com/search?q=repo%3Acode-charity%2Fyoutube%20http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg&type=code and they are being manually created with icons stored all over the codebase, now all icons should be moved …
=> Update core.js blocklist: safety, properly initialize, speed

background.js, js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/player.js, js&css/web-accessible/www.youtube.com/shortcuts.js, menu/skeleton-parts/shortcuts.js
Fixes:
- handlers dont lose state when hovering over text areas etc
- handlers didnt keep track of pressed keys well and lost events (still possible when debugging and ALT-Tabbing)
- added **developer warning** on top of shortcuts.js about debugging eating keypresses.
- scroll wheel shortcuts work more reliably
- shortcuts are validated during initialization
- shortcuts are now updated on settings change = no more needing reload page after shortcut changes
- renamed Quality shortcuts to more intuitive names, simplifies code a lot
- rename 'shortcut_volume_step', 'shortcut_playback_speed_step' to 'shortcuts_volume_step', 'shortcuts_playback_speed_step' to not mix variable keys with function Shortcuts. shortcut_ = shortcut; shortcuts_ = helper variable;
- auto update old Quality shortcuts …
=> Update shortcuts.js handlers rewrite, multiple fixes

js&css/web-accessible/www.youtube.com/appearance.js
ImprovedTube.descriptionSidebar was undefined without undoTheNewSidebar, this is why proper code indentation is so important, just clicking auto align in IDE would reveal this bug
=> Update appearance.js ImprovedTube.descriptionSidebar undefined

.github/workflows/build-safari-app-manual.yml, .github/workflows/build-safari-app.yml
Fixed typo in file of workflow
Added a manual version, just need to key the tag name and it will create and upload safari file to the release with the tag
=> Updated Safari Workflow

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/blocklist.js
=> Update blocklist.js cover three currently known versions of HTML #2422

js&css/extension/www.youtube.com/general/general.css, js&css/extension/www.youtube.com/styles.css
1 prevent "includes paid promotion"  from obscuring Blocklist buttons
2 make HIDE BUTTONS ON THUMBNAILS also cover video-preview
https://github.com/code-charity/youtube/issues/2423
=> Update general.css HIDE BUTTONS ON THUMBNAILS also cover video-preview

js&css/web-accessible/functions.js
Switched language and 'ytd-c4-tabbed-header-renderer' became 'yt-subscribe-button-view-model-wiz' somehow
=> functions.js channel not initialized on international YT

_locales/en/messages.json, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/appearance.js, js&css/web-accessible/www.youtube.com/player.js, js&css/web-accessible/www.youtube.com/shortcuts.js, menu/satus.js, menu/skeleton-parts/player.js, menu/skeleton-parts/settings.js, menu/styles/sub-options.css
- new Option "Auto-PiP only outside source Tab" https://github.com/code-charity/youtube/issues/1850
- dont Auto PiP paused videos https://github.com/code-charity/youtube/issues/1352
- adds warning about current Chrome limitations "PiP requires recent User interaction with source page. This is Chrome Picture-in-Picture API limitations and we cant do anything to bypass it. Works best with Autoplay disabled and manual Play control or deliberately clicking somewhere on the page before switching Tabs."
- checks to not throw errors in FF/browsers not supporting Chrome PiP API.
- hiding Auto PiP Options altogether in FF/browsers not supporting Chrome PiP API https://github.com/code-charity/youtube/issues/2051
- dont "Auto-pause while I'm not in the tab" if User engaged Chrome PiP manually …
=> fixing PiP / Auto PiP

js&css/web-accessible/www.youtube.com/player.js
Fixed fit to window (Issue #2516)
https://github.com/user-attachments/assets/32a0248a-7e6b-47e7-8564-0ba1b5484278
=> Fixed fit to window

js&css/extension/www.youtube.com/appearance/sidebar/sidebar.css
This should fix #2648 and fix the feature that I added in #1356 cause by Youtube changes
=> Sidebar fix

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/player/player.css, menu/skeleton-parts/appearance.js
In this PR I worked on issue #2668 which added a new feature that allows users to remove the chapter title button from the YouTube progress bar, enhancing the user experience by preventing accidental clicks on chapter titles that lead to unwanted scrolling.
=> Issue #2668 - Remove Chapter Title Button from YouTube Progress Bar

_locales/en/messages.json, js&css/extension/www.youtube.com/general/general.css, js&css/web-accessible/init.js, menu/skeleton-parts/general.js
This pull request works on issue #2670  removes the dots from the thumbnails.
Please review and let me know if any additional changes are required.
Before:
After:
=> issue #2670 - Feature to remove thumbnail dots

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/player/player.css, menu/skeleton-parts/appearance.js
This PR addresses issue #2680 by adding an option to the menu to remove the line under the caption button.
Please let me know if any adjustments or further changes are needed. Thank you!
=> Added functionality to remove the red line under the caption button.

_locales/en/messages.json, js&css/extension/www.youtube.com/general/general.css, menu/skeleton-parts/general.js
This PR addresses issue #2681 by implementing functionality to hide members-only videos. I added a toggle button at the end of the General section for users to enable or disable this feature.
https://github.com/user-attachments/assets/ce091855-6d95-4156-9fd3-4b61037f89a1
If there are any additional changes or suggestions, please let me know. Thank you!
=> Added feature in which users can remove members only videos

_locales/en/messages.json, js&css/extension/www.youtube.com/general/general.css, js&css/web-accessible/init.js, menu/skeleton-parts/general.js
This PR addresses this issue #2671. This PR introduces a feature to hide YouTube thumbnails on the homepage and elsewhere using dynamically injected CSS. The solution ensures that thumbnails are hidden without modifying the underlying structure of YouTube’s DOM. 
- Check into this branch locally 
- Navigate to `chrome://extensions/`
- In the top right cornet, toggle developer mode on.
- In the top left, click on the `Load unpacked` button
- Select the root folder where the `manifest.json` file leaves
- This should add the extension locally to your browser
- Navigate to `https://www.youtube.com`, confirm that the thumbnails for the front page videos are hidden.
- Look at the snippet below to confirm the change.
https://github.com/user-attachments/assets/8503bc0c-7405-4304-9323-6e417f63d6e6
=> Issue #2671 - Remove the thumbnail icon the front page

js&css/extension/www.youtube.com/appearance/player/player.css, js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/appearance.js, menu/skeleton-parts/player.js
Adds a new player setting to hide the progress bar preview and tooltip when hovering over the progress bar.
=> feat: add option to hide progress bar preview

js&css/web-accessible/core.js
This pull request is an attempt to close #2700.
Now, without having to _reload_ the page, the user should be able to hide and show `ImprovedTube's Cinema Mode` button.
https://github.com/user-attachments/assets/f16bb218-a291-447e-8484-ff5403662928
=> feat: hide cinema mode button on YT when the setting is disabled

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/player/player.css, menu/skeleton-parts/appearance.js, menu/skeleton-parts/player.js
This pull request attempts to close #2634.
As discussed in #2634, certain videos include a clickable link on top of the video titled, `Includes Paid Promotion` as shown in the video below:
https://github.com/user-attachments/assets/5a67afbb-2bb1-4991-bf4f-4ad20b29ef76
With the changes made, the extension now _hides_ the HTML elements related to the `Includes Paid Promotion` link:
https://github.com/user-attachments/assets/d4772053-d1cf-40d5-abe3-0e4b86c61546
Please let me know if there's anything else I should change - I'm happy to learn and fix more issues!
=> feat: add styles to hide 'Includes Paid Promotion' elements

js&css/extension/www.youtube.com/general/general.css
Fixes https://github.com/code-charity/youtube/issues/2777
Previously, member-only video hiding only worked on the home page. Now the functionality has been extended to both the home page and videos tab.
=> hide member-only videos in rich item renderer

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/details/details.css, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/appearance.js, menu/skeleton-parts/appearance.js
=> Show exact date button

_locales/en/messages.json, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, menu/skeleton-parts/player.js
This PR implements the feature requested in Issue #2798 : Prevent playback looping of youtube shorts video
- New option: Click on the "Player" icon in the extension and toggle the "Prevent short videos from auto-looping" option.
=> Issue 2798:Prevent playback looping of youtube shorts video

_locales/en/messages.json, js&css/extension/init.js, js&css/extension/www.youtube.com/general/general.js, menu/skeleton-parts/general.js
This should solve the issues #2910,  #2904, and #2905 
Added a dropdown in the menu General, subsection Thumbnails, with 5 options to choose from
Should be updated in real time and saved for future interactions with YouTube.
Is also working on the Subscriptions page on grid mode, seems to not be perfect, though, I noticed some visual bugs, like when selecting 6 videos appearing 5, I had to refresh the page to fix but wasn't 100% on all rows, also could vary depending on the size of the your tab, so maybe need some more adjustments, but for the Home page seems fine.
Also, I tested on an Ultrawide Quad HD monitor (3440x1440), so for sure will work differently on smaller monitors/resolutions, let me know about it.
Tested on both Chrome and Edge.
=> Improved the thumbnails per row adding more options to choose.

js&css/web-accessible/www.youtube.com/appearance.js
This should solve the issues #2925, and #2935 
Tested on both Edge and Chrome.
The change was literally adding a span inside the ytp-time-display class element, but also an important part was the code at the top of the function, which hides the div responsible for showing the "normal" duration time of the videos.
Once the toggle is off, this div should show normally as expected.
If the toggle is on and you change it to off, the changes will not affect the actual video in real time, and for this, a refresh on the page is necessary. I tried to solve this using CSS manipulation, but I got too many issues that were not worth the effort.
=> Fixed the remaining duration time bug.

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/details/details.css, js&css/web-accessible/www.youtube.com/appearance.js, menu/skeleton-parts/appearance.js
This PR introduces a new appearance option to disable the animated "slot machine" effect for the YouTube likes counter. When enabled, the likes count is shown as a static, properly aligned number, improving readability and accessibility for users who prefer a non-animated display.
**Key changes:**
- Adds a toggle ("Disable likes animation") to the Appearance > Details menu.
- Localizes the new option for English (with easy extensibility for other languages).
- Updates JavaScript to replace the animated likes counter with a static number and sets a CSS attribute for styling.
- Adds CSS to hide the animated counter and ensure the static number is visually aligned and uses tabular numerals.
- Ensures the feature works on page load and navigation events.
| Before | After |
|--------|-------| …
=> feat(disableLikesAnimation): Added option to disable animated likes counter on YouTube and display static, aligned number

js&css/extension/www.youtube.com/appearance/header/header.css
This should solve the issue #2939 
I tested on Chrome and Edge, as usual. 
This should only affect the home page, the original functionality was not affected, e.g on YouTube video page.
=> Fixing the duplicated YouTube logo

js&css/extension/www.youtube.com/appearance/player/player.css
Fix: Always show progress bar (Fixes #2946)
This fix addresses the issue where enabling the 'always show progress bar' feature causes the red ball (scrubber button) to freeze and not follow the progress bar. The solution hides the red ball when the feature is active, improving the UI as the red ball appears misplaced otherwise.
Details
Issue: When the 'always show progress bar' feature is enabled, the red ball (scrubber button) freezes and fails to track the progress bar correctly.
Solution: Added CSS to hide the scrubber button when the feature is active:
[data-always-show-progress-bar="true"] .html5-video-player:not(.ytp-mini-player).ytp-autohide.ytp-chrome-bottom .ytp-scrubber-button {
display: none !important;
}
Tested in Chrome with ImprovedTube version 4.1250.
Verified that this fix …
=> Fix: Always show progress bar (Fixes #2946)

js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/appearance.js
This should solve issue #2951 and show the time remaining as shown in the image below
Also, this commit improve the way to both time remaining and "normal time" appears, changing in real time both, so will not be necessary to reload page after you toggle on/off the "Show video remaining duration" option.
Tested on Chrome and Edge.
=> Fix to the remaining time duration

js&css/extension/www.youtube.com/general/general.js
This is an improvement from PR #2936.
[@MisterTickle](https://github.com/MisterTickle) commented that it was not working on the Subscriptions page, and indeed was not good enough, sometimes worked, sometimes not.
Since YouTube treats each page a bit differently, I had to look for all elements on the Subs page for the specific class, --ytd-rich-grid-items-per-row, and then apply the number of items. 
If you still see something strange visually, like some rows with only 2 videos, is because of the Shorts; disable them and it should work perfectly. But even if you like shorts, this only happens in 2 to 3 rows at maximum, so it is not a huge problem.
Tested on both Chrome and Edge, and also confirmed that the previous code for the Home page is working fine; the change was only for the …
=> Improve thumbnails per row on the Subscriptions page

js&css/web-accessible/www.youtube.com/player.js
This is an improvement from PR #2957.
I was testing [this video](https://www.youtube.com/watch?v=DZIASl9q90s), which has a lot of audio dub tracks, so is pretty good to test, and I found an issue.
My fix is simple and just add a new validation to get the original track from another variable, depending on the video, this can happen, so this is more like a covering all bases scenario.
Tested on Edge, but the code should work on all browsers.
=> Fix to catch more scenarios for "Disabling AI auto-dub feature"

_locales/en/messages.json, js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/appearance.js, js&css/web-accessible/www.youtube.com/player.js, js&css/web-accessible/www.youtube.com/shortcuts.js, menu/skeleton-parts/appearance.js, menu/skeleton-parts/player.js, menu/skeleton-parts/shortcuts.js
This feature is closely related to #1463, adding a button below the player
That allows us to jump to what I call "Key Scene" but is basically to jump to the "Most viewed" parts on a video, including videos with multiple most viewed moments.
It has one issue, though, because when you click on a video from a sidepanel the Youtube actually don't refresh the page, it will not work, it will try to jump to the timestamp from the previous video, the easy way to "solve" this is basically refreshing the page or opening every new video in a new tab, both have the same effect, which is to force the YouTube to refresh the page, so the feature will work fine in this case.
Tested on Chrome, Edge, and Firefox.
@ImprovedTube, let me know what you think.
=> Feature: Adding a button below player to jump to the next key scene(s)

js&css/web-accessible/www.youtube.com/appearance.js
This should fix the issue mentioned in #3007 
Tested on Edge, Chrome.
=> Ignoring the remaining time duration if the video is a live stream

js&css/extension/www.youtube.com/appearance/sidebar/sidebar.css
Fixes issue #2972
In **Appearance > Sidebar > Move thumbnails to the right!**, the thumbnails for playlist items remained aligned to the left, unlike regular video suggestions which moved correctly. This broke the visual consistency of the sidebar layout.
YouTube is now rendering some playlist suggestions using a new layout system.
This PR updates the ImprovedTube stylesheet to handle both layouts:
- Applies `flexbox` to the new container.
- Reverses the direction so that playlist thumbnails appear on the right, matching the behavior for videos.
_Source: from the original issue description_
_Source: screenshot from my laptop_
Let me know if any tweaks are needed — happy to iterate!
Thanks,  
Aviral Dewan
=> fix: playlist thumbnails move to right when the feature is turned on

_locales/en/messages.json, js&css/extension/core.js, js&css/extension/init.js, js&css/extension/www.youtube.com/general/general.css, js&css/extension/www.youtube.com/general/general.js, menu/skeleton-parts/general.js
| Category     | Details                                                                 |
|--------------|-------------------------------------------------------------------------|
| Problem      | No way to remove sponsored videos on home page                          |
| Solution     | Added toggle to hide them cleanly without leaving gaps                  |
| Alternatives | Used scripts before, but they left empty space or broke layout          |
| Scope        | Improves experience for users who dislike sponsored content             |
| Side effects | None – feature is isolated and optional                                 |
| Context      | fixed Issue [#3073](https://github.com/code4charity/YouTube-Extension/issues/3073) |
**🎥 Demo Video:** [Watch …
=> added option to hide sponsored videos on YouTube home page #3073

build/build.py
This PR fixes the build.py script so that it generates a zip-file which can be used in Firefox's Load Temporary Add-on.
=> Fix the build script for Firefox

CONTRIBUTING.md, LOCALE_KEY_NAMING_ISSUE_REPORT.md, _locales/zh_CN/messages.json
The YouTube extension failed to pack due to invalid locale key names in the Chinese (Simplified) locale file (`_locales/zh_CN/messages.json`). Chrome extensions have strict naming conventions for locale keys that only allow ASCII letters (a-z, A-Z), numbers (0-9), and underscores (_).
Several locale keys in the Chinese locale file contained invalid characters, including:
- Spaces
- Apostrophes (')
- Exclamation marks (!)
- Parentheses ()
- Special Unicode characters (⫶)
- Hyphens (-)
The following invalid keys were identified and corrected:
| **Invalid Key Name** | **Corrected Key Name** | **Status** |
|---------------------|----------------------|-----------|
| `"Disable video playback on hover"` | `"disableThumbnailPlayback"` | ✅ Fixed |
| `"Dim Youtube's Pages, except what I …
=> Fix the zh_CN tranlation

_locales/de/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
- Add toggle-able playback speed button in player controls
- Left click: set to custom speed from settings (default 1.25x)
- Right click: reset to 1.0x normal speed
- Mouse wheel: adjust speed in configurable steps (default 0.1x)
- Speed range: 0.0625x to 16x (browser limits)
- Added to Player  Buttons settings section
- Multi-language support: EN, ES, FR, DE
- Integrates with existing playback speed system
- Uses existing shortcuts_playback_speed_step setting
- Uses existing player_playback_speed setting for custom speed
Resolves: Quick access to playback speed without gear menu navigation
=> feat: Add playback speed button to player controls

js&css/extension/www.youtube.com/night-mode/night-mode.js, menu/skeleton-parts/night-mode.js
When the time at the start of the video page is within the schedule time, nightmode no longer needs to refresh when altering with dim and schedule times.
However, nightmode's dim is locked, but not reset to 0 when outside of the schedule time frame. Also, nightmode does not auto-switch into the proper schedule while the video is playing until the page is refreshed as the time is only collected at the start of the webpage.
It's supposed to address Issue #3136.
Tested with Firefox's Temporary Add-ons and Google's Developer Mode on Extensions.
=> Fix: Nightmode Without Refreshing (Partial) Issue #3136
