chrome/_locales/nl/messages.json
=> Added Dutch translation

2.0/_locales/pt_BR
=> Translation to Brazilian Portuguese

_locales/pt_BR/messages.json
Additions according to english version 2.1:
"bubbles"
"list"
"items"
"styles"
"icons"
"video"
"audio"
"style"
"categories"
"empty"
"thisWillRemoveAllYouTubeCookies"
=> Brazilian Portuguese

youtube/css/appearance.css
Updated appearance.css to remove blank space between like/dislike icons when "icons only" options is selected.
=> Updated appearance.css to remove blank space

_locales/ar/messages.json
These words do not change
- Active features
- Block all "Player > Ads > Block all"
- Search...
https://imgur.com/a/7JroqB2
In all languages, not just Arabic
=> better translation

_locales/ru/messages.json
Аdditional translation and cosmetic/grammatic improvements
=> Update Russian translation

_locales/ja/messages.json, popup.js, src/template/js/index.js, src/template/js/template-parts/header/settings.js
I added Japanese translation. Please merge it.
I tested ImprovedTube on "Chromium 81.0.4044.113 Arch Linux".
Thank you for providing a good extension.
=> Add Japanese translation

_locales/nl/messages.json
=> Updated Dutch translation

_locales/sk/messages.json
=> Slovak translate

_locales/id/messages.json
Very basic indonesian language, I will try to fix translation if it's doesn't fit the UI.
=> Indonesian Language (Bahasa Indonesia)

_locales/id/messages.json
Update to fit UI & fix language error.
=> Update for Bahasa Indonesia

_locales/ko/messages.json
translation KO (Korean)
한국어 by [msc9533](https://github.com/msc9533)
=> translation KO (Korean)

README.md, _locales/de/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/id/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pt_PT/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_TW/messages.json
Keep proper and consistent service naming in documentation and translations.
- Replaced "Github" with "GitHub"
- Replaced "Improvetube" with "ImproveTube"
- Replaced "Youtube" with "YouTube"
=> Replace service names

_locales/ar/messages.json, _locales/de/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, content-scripts.js, popup.js, src/template/js/template-parts/shortcuts.js, src/youtube/js/features/shortcuts.js
I have no idea what's going on with all the changes on blank lines, "ImprovedTube.volumeMixer = function() {};" and some brackets. I tried 3 times to clone it clean and add my changes but they still appear. Anyway, the new feature added works fine.
=> Added enhancement #298

satus.js
All keybindings's reset function work now.
=> Fixed #513

src/youtube/css/appearance.css
If Show card on mouse hover option enabled and On Mouse hover event, it will show output like this,
- It will not show (I) icon at all as "Show card on mouse hover" option enabled.
=> FIX: BUG: Cards not showing at all and a NULL notice button #536

_locales/zh_TW/messages.json
This PR aims to improve the translation quality of the existing Chinese (Traditional) (`zh-tw`) localization by translating non-translated strings and relocalizing improperly localized strings.
=> Improve zh-tw Translations

_locales/bn/messages.json
Added Bengali Lang Translation for Plugin
=> Added Bengali Lang Translation

_locales/hin/messages.json
Added translation for hideGradientBottom and statsForNerds
=> Added more `hin` translations

_locales/zh_CN/messages.json
added and improved some translations.
=> Added more 'zh_CN' translations

_locales/fr/messages.json
Everything has been translated, but some lines might be too long.
=> Translation to french (100 %)

_locales/de/messages.json
I offer a complete German language update. Corrected some grammar errors and general improvements, also tried to adapt the function names on YouTube to German to avoid comprehension problems. Regards :)
=> Full German Support

_locales/el/messages.json
el directory added in the _locales directory and strings in messages.json translated to Greek
=> Added Greek Locale Translation

_locales/es/messages.json
Simply added a few translated lines :)
=> Added missing Spanish translations

_locales/es/messages.json
Just fixed some typos / incorrect lines, aswell as improved some *not quite fitting* ones
=> fix / improved Spanish translations

src/youtube/css/player.css, src/youtube/js/features/player.js
Fixed issue #593
Am I right that I should change only these files and they will be combined into `content-scripts.js` and `content-scripts.css` automatically?
=> Fix timeline in mini-player

_locales/tr/messages.json
A change that corrects the word mistake
=> Correcting the Word Error

popup.css
=> Fix issue of overlapping text with icon for non english language

background.js, content-scripts.js, content-styles.css
Fixes in css file and a bit of clean code in js
=> Small fix and improvement

background.js, manifest.json, youtube-scripts.js
resolves code4charity/YouTube-Extension#774
=> popout player playlist support

_locales/en/messages.json, _locales/messages.json, popup.js, youtube-scripts.js
Forgot to merge this, makes it possible to assign shortcuts, I like to use ctrl + arrow up
=> ADD shortcut for pop-out player

youtube-scripts.js
Added a check to only set video quality at initial video load, allowing quality to be changed manually.
Fixes #813 and #828.
=> Fixed stuck video quality

_locales/en/messages.json, popup.js, youtube-scripts.js
_(Resubmitting PR after repo reorganization)_
Added a shortcut to toggle autoplay. See #821.
Also detabbed a few existing lines of code to fit conventions.
=> Added autoplay toggle shortcut

_locales/en/messages.json, popup.js, youtube-scripts.js
_(Resubmitting PR after repo reorganization)_
+ Option "Hide player controls" will permanently hide the YouTube player overlay until the option is disabled (or toggled via shortcut)
+ New shortcut that allows toggling of the player controls while watching a video.
=> Added option to hide controls & shortcut to toggle them

youtube-scripts.js
Fixed an issue where the aspect ratio did not match the actual screen size when using the rotation button. 
Fixes #783
=> Fix rotation button behavior

README.md, _locales/hr/messages.json
Added translations for Croatian (Hrvatski) language, changed README.md & added new files to _locales (_locales > hr > messages.json)
=> Added translations for Croatian (Hrvatski) language

_locales/zh_TW/messages.json
This PR updates the localization file for zh-tw and adds the missing keys.
=> Update zh-tw localization

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/hr/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pl/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ro/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, popup.js, youtube-scripts.js
=> Implemented feature #946

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/hr/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pl/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ro/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, content-styles.css, popup.js, youtube-scripts.js
Add feature for #981
There is a small bug, idk why it is not working for initialization (when refresh the video, the css code is not injected) but when i off and on the option in the menu, the css get injected
=> Added new feature "hide 5 seconds skip overlay"

_locales/en/messages.json, _locales/pl/messages.json, popup.js, youtube-scripts.js
… and delete History
Privacy oriented patch according to my comment in #482
English and Polish locales updated for added options. Is there a way to automate google translating the rest?
=> Added Watched Videos History Management - ability to disable tracking

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/hr/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pl/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ro/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, popup.js, youtube-scripts.js
=> Added "video remaining duration" to Translation file

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/hr/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pl/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ro/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, content-scripts.js, content-styles.css, popup.js, youtube-scripts.js
Added 3 different option:
- normal
- overlay (side bar will not take the right width space which fix #164)
- hidden (you will not see the side bar but user are still able to scroll)
=> Added "Custom scroll bar" feature

_locales/bn/messages.json, _locales/hin/messages.json
Updated HIN and BN translations
=> Updated all Remaining Translations

_locales/ar/messages.json, _locales/bn/messages.json, _locales/de/messages.json, _locales/el/messages.json, _locales/en/messages.json, _locales/es/messages.json, _locales/fr/messages.json, _locales/hin/messages.json, _locales/hr/messages.json, _locales/id/messages.json, _locales/it/messages.json, _locales/ja/messages.json, _locales/ko/messages.json, _locales/nb_NO/messages.json, _locales/nl/messages.json, _locales/no/messages.json, _locales/pl/messages.json, _locales/pt_BR/messages.json, _locales/pt_PT/messages.json, _locales/ro/messages.json, _locales/ru/messages.json, _locales/sk/messages.json, _locales/tr/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, content-styles.css, popup.js
Feature requested by the 2 issues below
resolve #1031 
resolve #695
=> Added "Hide player control options" feature

youtube-scripts.js
Fixed "Remaining Duration" feature when off in-between video, need to refresh the page for the "Remaining Duration" element to be remove
fix #941
=> Fixed "Remaining Duration" feature

youtube-scripts.js
Fixed "next shortcut" feature not looping playlist when click
fix #1035
=> Fixed "next shortcut" feature

youtube-scripts.js
This change basically mimics what youtube player does when you manually
change the volume.
=> Make increase/decrease volume shortcuts changes persistent

content-styles.css, youtube-scripts.js
=> Fixed Player button for player alignment

content-styles.css, ui/script.js, youtube-scripts.js
fixes #229
fix video upload time and channel video count
fix typo of google_api_key
introduce const for default hardcoded api key
=> fix functionality which uses api key

_locales/nl/messages.json
- Revised a bunch of Dutch words, mostly for to improve clear language and prevent misinterpretations
- Revised some language more to Dutch style (i.e. combining of words / removing whitespace)
- Some translations were in English: translated them to Dutch
Don't know the real context of some used terms, so in some cases small revision might be necessary.
Maybe I should test my fork first? This is my first pull request ever so all advice is welcome. :)
=> Update of Dutch language

_locales/nl/messages.json
Received JS error upon installing the extension. 
Closing the quotations fixed it.
=> Fixed missing quotation marks.

_locales/ro/messages.json
hi! 🤩 @hateofhades 
@alexandrubo
=> Some words are not translate to romain and i do it

youtube-scripts.js
Did some minor change to the code to optimize some part of the it.
=> Improved code performance

ui/script.js, ui/styles.css
[#1223](https://github.com/code-for-charity/YouTube-Extension/issues/1223) Moved button to not obscure elements in List view
=> Moved report bugs button to settings

_locales/en/messages.json
all but one use of color is "colour".
=> Keep consistency with the word "color"

_locales/zh_TW/messages.json
Fix some minor translations and also add some new!
=> Update messages.json of zh_TW(Traditional Chinese)

_locales/es/messages.json
Added translations and updated others o.o
=> Update messages.json (Spanish Translation)

_locales/vi/messages.json
If there is a spelling error or other error in the first translation, I or someone else will update it. Thank you.
=> Added Vietnamese translation

content-styles.css
add object fit property for fit to container
=> fix video fit to container

youtube-scripts.js
Did a bit of rearranging of ytElementsHandler code to optimization the performance as shown below.
=> Code optimization

content-styles.css
=> Fix comment avatars not displaying when disabling "Hide Avaters"

content-styles.css, ui/script.js, youtube-scripts.js
Fix and improvement on the hide thanks button feature cause by YouTube update
=> Player detail

youtube-scripts.js
~~Fix an issue where hideDetailButton() causes the plugin to stop working, and~~ fix a bug where autoplay would not always be toggled. See commit notes for more details. Hopefully addresses #1241.
=> Fix an issue with toggle autoplay

content-styles.css
Improve header position to fit new YouTube homepage and added the left navigator collapse button to left navigator so that when header is hidden, user can still collapse the left navigator.
Before:
After:
=> Improve Header position

youtube-scripts.js
=> Fix playlist repeat not working

youtube-scripts.js
=> Fix playlist repeat

content-styles.css
Remove empty space when nothing is at the sidebar
Before:
After:
=> Improved sidebar

content-styles.css, manifest.json
=> Fix player element overlap

youtube-scripts.js
=> Fixed forced theater mode not working

youtube-scripts.js
Removed repeated function
Improved expand description function
Fixed error found on yt-page-data-updated event function
=> Minor changes

_locales/en/messages.json, ui/script.js, youtube-scripts.js
=> Rework playback speed to be more intuitive

youtube-scripts.js
=> Fix playlist autoplay ( #1412 / #1198 )

.github/README.md
Fully reworked README.md to look better and work better on different sized displayed.
@ImprovedTube Stuff like Planned Features and other things are not fully filled out as I am not exactly sure what to put there.
=> Cleanup & rework README.md

_locales/it/messages.json
There were some lines that were not translated so I did
=> Update italian messages.json

_locales/tr/messages.json
Update for missing translations
=> Update for missing translations

_locales/ru/messages.json
- Corrected some phrases and words.
- Wrote the missing localization.
=> Added Russian localization

_locales/it/messages.json
I've translated some more lines to Italian
=> Updated italian translation

_locales/ko/messages.json, content-scripts/website-context/youtube-features/appearance.js, options-page/skeleton-parts/appearance.js
I added untranslated parts, corrected typos, and translated them more intuitively.
=> Modifying Korean Translation

background.js, content-scripts/extension-context/init.js, content-scripts/website-context/core.js, content-scripts/website-context/youtube-features/appearance.js
=> Revert "Modification to fix  issue #1516"

menu/skeleton-parts/appearance.js, menu/skeleton-parts/general.js, menu/skeleton-parts/player.js, menu/skeleton-parts/settings.js, menu/skeleton-parts/themes.js
fix mixing naming conventions
, spaces to tabs, unified formatting
=> Raszpl patch 1

js&css/satus.js, menu/skeleton-parts/player.js
slightly clearer messaging about disabled vital codecs
updating detection with codec currently used by YT
=> Raszpl patch 2

.github/README.md, _locales/fa_IR/messages.json
Add Persian (Iran) language and editing the necessary sections for the `README.md`
=> Add Persian language

js&css/web-accessible/www.youtube.com/player.js
From simply clicking non-existent 'Skip Ad' button to force seeking ads video.
=> fix(player): Renewed skip ad mechanism

_locales/zh_TW/messages.json
=> Update zh_TW Traditional Chinese locale

js&css/extension/www.youtube.com/appearance/player/player.css
Added an exception to the "Full-Height" Player size style for theater mode that was breaking fullscreen mode. fixes #1722
=> Added an exception for full-height theater mode size so it doesn't break fullscreen. fixes #1722

js&css/extension/core.js, js&css/extension/www.youtube.com/appearance/comments/comments.css, js&css/extension/www.youtube.com/general/general.css, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/appearance.js, js&css/web-accessible/www.youtube.com/channel.js, menu/skeleton-parts/channel.js
This is a 'Compact Theme' for the subscriptions accordion/sidebar.
- Allows to collapse _'Subscriptions'_ , _'Explore'_ and  _'More from Youtube'_ sections
- The state is persistent (localStorage)
- Currently doesn't work when no user is logged
___
<details>
<summary><b>Comments</b></summary>
I've placed the feature in `Channel` section, but I don't think it's the most appropriate place to be put; it needs a rename as well. You'll handle that.
Apart from small typos among files, shifted `flex-direction: row` from CSS to JS as it should've been from the beginning (it now works properly on no-logged YouTube). 
</details>
=> Compact theme feature

js&css/extension/www.youtube.com/appearance/player/player.css
https://github.com/code-charity/youtube/issues/1740
replace #player-wide-container with #player-full-bleed-container
=> Fix: #1740

js&css/web-accessible/www.youtube.com/blacklist.js
=> try to fix blacklist for new "@channelname format"

.github/README.md, _locales/sv/messages.json
Addition of a Swedish translation & edits of corresp. parts in README.md
=> Addition of a Swedish Translation

js&css/extension/www.youtube.com/general/general.css
fix the `:has()` selector compatibility issue as the solution mentioned in [comment](https://github.com/code-charity/youtube/issues/1779#issuecomment-1751546105)
=> fix: #1779

_locales/en/messages.json, _locales/en_US/messages.json, background.js, js&css/extension/init.js, js&css/extension/www.youtube.com/general/general.js, menu/skeleton-parts/general.js
Addressing issue #1774,
Now users can select if they want to open a new tab for the search.
new feature option is in: General menu
=> feat: show searched video in new tab. issue #1774

_locales/tr/messages.json
Fixed missing parts and errors
=> Update tr messages.json

js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/player.js
More info in issue #1805 section [1].
When the video popup button is clicked, search the URL for a playlist and, if found, include it in the popup window.
=> Added playlist to video popup button ( #1805 [1] )

js&css/extension/www.youtube.com/appearance/comments/comments.css, js&css/extension/www.youtube.com/appearance/player/player.css, js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
Reverts code-charity/youtube#1798
=> Revert "'Fit To Window' Player button"

js&css/web-accessible/www.youtube.com/player.js
More details in #1812 
Now, when the popup opens (with a playlist), it checks if the video playing is the correct one, and if not, reloads with the playlist removed (should play the correct video)
=> Fixed video popup with playlist ( #1812 )

js&css/web-accessible/www.youtube.com/player.js
=> bugfix: undefined it-player-size in FitToWin button

js&css/web-accessible/www.youtube.com/player.js
This PR is resolving the issue mentioned in #1840, have a look @ImprovedTube now it is working fine, please merge the PR.
=> screenshot and repeat active/inactive issue

js&css/web-accessible/www.youtube.com/blocklist.js
I moved the id and hide video part up and added a check to prevent multiple block buttons, also there was a bug with video titles not being added, so I changed `parentNode` to `__dataHost` and the blocklist didn't work on channel pages for me either, so I also fixed that part I guess.
=> fix #1865 and some other blocklist bugs

.github/README.md, _locales/es/messages.json, _locales/es_419/messages.json
Hi @ImprovedTube , I've corrected some of the existing spanish translations and added missing ones.
=> Improve spanish translation

js&css/web-accessible/www.youtube.com/player.js
Fixes #1898 
I would like to claim the bounty offered.
What does this PR do?
Adds the feature which embeds subtitle inheriting the subtitle customization from the extension.
Following is the example
=> fix: Embeds subtitle on saved screenshots

js&css/extension/www.youtube.com/appearance/sidebar/sidebar.css
I corrected the error.
Issue nr 1905
=> live chat strech issue 1905 fixed

_locales/en/messages.json, js&css/extension/www.youtube.com/appearance/comments/comments.css, menu/skeleton-parts/appearance.js
Following @ImprovedTube guidance, I have added to appearance.js, updated description to _locales/en/messages.json, and the [it-columns=true] to user setting attributes.
=> Added Column Toggle Feature (2nd Time)

js&css/web-accessible/functions.js
https://github.com/code-charity/youtube/issues/2058
=> functions.js node.$['flexible-item-buttons'].children issues/2058

menu/satus.js
=> Search fix, use translation list keys as a database for searching

js&css/extension/www.youtube.com/appearance/player/player.css
https://github.com/code-charity/youtube/issues/2066
=> fix "5 second skip animation" CSS, player.css issues/2066

js&css/extension/www.youtube.com/styles.css
#1971  make the blacklist button visible
=> Update styles.css issues/1971 make the blacklist button visible

menu/styles/themes.css
https://github.com/code-charity/youtube/issues/2083
=> Update themes.css plain ui glitch

js&css/extension/www.youtube.com/appearance/header/header.css
https://github.com/code-charity/youtube/issues/2069
also fixes static header top gap
big z-indexes dont do much other than attracting ad filters
=> header.css fix Transparent top bar stops working when scroll

js&css/extension/www.youtube.com/appearance/header/header.css
https://github.com/code-charity/youtube/issues/2069
=> fix transparency when ytd-masthead[frosted-glass]

background.js
make sure hideSubscribe is updated only once, formatting/indentation, fixing basic linter found bugs.
=> background.js hideSubscribe only once

js&css/web-accessible/www.youtube.com/settings.js, menu/skeleton-parts/settings.js
fixed https://github.com/code-charity/youtube/pull/2123 thus fixed https://github.com/code-charity/youtube/issues/2082
=> settings.js adding Disabled Language option

_locales/el/messages.json, _locales/es/messages.json, _locales/fa/messages.json, _locales/fr/messages.json, _locales/it/messages.json, _locales/ko/messages.json, _locales/no/messages.json, _locales/pt/messages.json, _locales/ro/messages.json, _locales/sr/messages.json, _locales/tr/messages.json, _locales/uk/messages.json
* New translations messages.json (Turkish)
* New translations messages.json (Romanian)
* New translations messages.json (French)
* New translations messages.json (Spanish)
* New translations messages.json (Greek)
* New translations messages.json (Italian)
* New translations messages.json (Korean)
* New translations messages.json (Norwegian)
* New translations messages.json (Serbian (Cyrillic))
* New translations messages.json (Ukrainian)
* New translations messages.json (Portuguese, Brazilian)
* New translations messages.json (Persian)
=> Turkish update and others messages modified

js&css/extension/www.youtube.com/appearance/header/header.css
Please let me know if there are changes to be made to this very code. Thank you.
=> fixed search bar transparent and search button

js&css/extension/www.youtube.com/styles.css
makes it look ok with all themes no matter if [dark] is set or not
=> Update styles.css override subscribe button when not subscribed

_locales/en/messages.json, menu/skeleton-parts/player.js
=> Update player.js autoplayDisable rename

menu/satus.js, menu/skeleton-parts/active-features.js
fixes https://github.com/code-charity/youtube/issues/2168
=> Update active-features.js show themes

js&css/extension/www.youtube.com/appearance/details/details.css, js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/appearance.js
Modifications per https://github.com/code-charity/youtube/issues/2171#issuecomment-2046151072
Please let me know if additional testing is needed. Thanks.
=> Added Fix for buttons below the player

_locales/el/messages.json
Changes:
-   Increased Coverage: Translation coverage has been expanded from 50% to 94% (crowdin)
-   Improvements: Some small improvements to show consistency and better understanding
=> Updated Greek Translations

js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/player.js
https://github.com/code-charity/youtube/pull/2212
=> Update player.js fixed playerQualityWithoutFocus

js&css/extension/www.youtube.com/general/general.css
=> Update general.css scrollbar in fullscreen fix #2268

js&css/extension/www.youtube.com/appearance/player/player.css
https://github.com/code-charity/youtube/issues/2278
=> Update player.css fix subscriptions

js&css/web-accessible/www.youtube.com/player.js
Channel trailers are #c4-player instead of #movie_player
=> Update player.js fix channel_trailer_autoplay

menu/satus.js
https://github.com/code-charity/youtube/issues/1446 first bug
mentioned in https://github.com/code-charity/youtube/pull/2312
=> Update satus.js fix shortcut reset

js&css/extension/www.youtube.com/appearance/header/header.css
Google servers different HTML to FF https://github.com/code-charity/youtube/issues/2372
=> Update header.css Firefox logo fix

menu/skeleton-parts/player.js
https://github.com/code-charity/youtube/pull/2292
https://github.com/w3c/battery/issues/25
=> Update player.js commenting out until feature is finished

js&css/extension/www.youtube.com/general/general.js
https://github.com/code-charity/youtube/issues/2315
=> Update general.js disableThumbnailPlayback search page fix

js&css/web-accessible/core.js, js&css/web-accessible/www.youtube.com/playlist.js
https://github.com/code-charity/youtube/issues/1720
checks all variables/properties it touches for max safety
=> playlist.js undefined 'playlistData' proper fix, even safer

js&css/web-accessible/functions.js, js&css/web-accessible/www.youtube.com/player.js
Continuing https://github.com/code-charity/youtube/pull/2385 . youtube is leaving shadow inactive player on navigating to subscriptions/home, was tripping up subtitle routines
=> Update player.js more subtitle safety

js&css/web-accessible/core.js, js&css/web-accessible/functions.js, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/channel.js
wasnt working with ytd-two-column-browse-results-renderer layout
switched it to createIconButton()
createIconButton extended, can create a icon buttons now
=> Update channel.js fix channelPlayAllButton

js&css/web-accessible/www.youtube.com/blocklist.js
YT tries to remove all forein nodes from node.parentNode.parentNode some time after 'yt-navigate-finish'.  Need to monitor for it and re-appendChild our button, otherwise if  gets deleted when switching to channel subpages /playlists /featured /videos etc.
=> Update blocklist.js Channel button Observer

background.js
ContextMenu links in German when language =='default'
linter errors, after https://github.com/code-charity/youtube/pull/2451  background.js becomes error free as far as linter goes :)
=> background.js ContextMenu links in German when language =='default'

js&css/web-accessible/www.youtube.com/channel.js
Fixed #2549 
https://github.com/user-attachments/assets/dc170457-7754-4d18-a395-3165897728e9
=> Fixed duplicated play all button when switch page

js&css/extension/www.youtube.com/appearance/player/player.css, menu/skeleton-parts/appearance.js
Youtube has moved from a red background color to a linear red-pink gradient in the progress bar.
I added a red and a default color in the option menu.
=> Issue #2615

js&css/extension/www.youtube.com/appearance/player/player.css
"background" was messing with "background-image" in HD.
Added colors in "overlay" and "mouse over" progress bar.
=> Issue #2630

js&css/extension/www.youtube.com/appearance/player/player.css
Added feature #2644.
Found all the new gradient youtube and replaced it.
=> feature #2644

js&css/extension/www.youtube.com/appearance/player/player.css, js&css/web-accessible/www.youtube.com/appearance.js, menu/skeleton-parts/appearance.js
After discussing it with other members of the Issue, I added this feature to mask out the pink loading bar above the video.Hope it can be helpful.If there is any problem,I'm willing to revise it!
=> Add Hide Top Progress Bar Function In Appearance Player

_locales/en/messages.json, js&css/extension/www.youtube.com/general/general.css, menu/skeleton-parts/general.js
This PR closes issue #2660. If there are any further changes that need to be made let me know, thank you!
Video:
https://github.com/user-attachments/assets/6180a521-c952-46c3-b610-313433549591
=> Added feature to remove context buttons from youtube shorts.

menu/index.html
This pull request attempts to close #2693, where there is an extra quotation in the HTML.
=> fix: remove extra quotation

js&css/extension/www.youtube.com/styles.css
Fix https://github.com/code-charity/youtube/issues/2706.
=> Add z-index for button tooltip.

_locales/en/messages.json
Previously when you went to player/Hide player control buttons the message for autoplay used to be in spanish. I have added in the messages.json support for english.
Before:
After:
If there any extra changes necessary let me know. 🚀
=> Added autoplay message in english

menu/satus.css
=> Fixed UI Layout Misalignment (#2705)

_locales/id/messages.json
fix untranslated message and add new translation key from language (en)
=> (id) fix untranslated message

.github/README.md, _locales/ur/message.json
Urdu translation was added to the project.
=> Urdu Translation Added

js&css/extension/www.youtube.com/styles.css, js&css/web-accessible/www.youtube.com/themes.js
Fixed bug identified in https://github.com/code-charity/youtube/issues/2907.
Before: As described in https://github.com/code-charity/youtube/issues/2907
Now:
=> Fix bug where themes show some wrong coloured section in the header (2907)

_locales/nl/messages.json
I changed a couple of words that sounds better like this.
=> Update nl language

js&css/web-accessible/www.youtube.com/appearance.js
This should fix the problem in #2951
=> Adding the current time to the logic of remaining time 

js&css/extension/www.youtube.com/styles.css
fixed the scroll issue due to the transform when selecting x-small and resize works with number of thumbnails per row
=> Resized thumbnails

_locales/en/messages.json, js&css/web-accessible/www.youtube.com/appearance.js, js&css/web-accessible/www.youtube.com/playlist.js, menu/skeleton-parts/player.js, menu/skeleton-parts/playlist.js, menu/styles/sub-options.css
This should solve #2969 
Working for both single videos and playlists.
=> Feature: Copy video full URL

_locales/en/messages.json, js&css/web-accessible/init.js, js&css/web-accessible/www.youtube.com/player.js, menu/skeleton-parts/general.js
https://github.com/code-charity/youtube/issues/3033
added the function to fix this issue
=> change shorts url to watch

_locales/ko/messages.json
- The last Korean translation update was in March 2023, so I have translated the newly added JSON entries into Korean.
- I tried to follow YouTube Korea’s official terminology as much as possible.
- The translations were aligned with the most recent version of `en/messages.json`.
- Existing translated content has been kept as is.
=> update Korean translation

js&css/web-accessible/init.js
Fixes #3098
I don't know if it's the best way to do it, but it works like this.
=> 🐞"Shorts: Force to use the standard player" not working

js&css/extension/core.js, js&css/extension/www.youtube.com/general/general.js
Hiding subscriptions in the sidebar currently does not work. This fixes it.
=> Fix hiding subscriptions in side panel

_locales/fa/messages.json
This pull request adds a full Persian (fa) translation for ImprovedTube.
- 505+ translated strings
- Based on the latest English `messages.json`
- Reviewed for consistency and accuracy
This will make the extension more accessible for Persian-speaking users.
=> Add Persian (fa) translation

.github/README.md, _locales/pt_BR/messages.json
- I translated the newly added JSON entries into Brazilian Portuguese. 
- The translations were aligned with the most recent version of en/messages.json. 
- Some minor spelling errors on the existing translation were fixed.
=> Update pt_BR translation  

.github/README.md, _locales/bn/messages.json, _locales/bn_BD
Bengali (Bangladesh) language added
=> added bn_BD.	

_locales/de/messages.json
I like the extension, but there were gaps in the German translation that are filled now.
=> feat(_locales): update German locale with missing translations and new features
